// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_org_api_keys

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OrgApiKeysDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Org ID (UUID)",
				MarkdownDescription: "Org ID (UUID)",
			},
			"org_api_keys": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"expires_at": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"last_used_at": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"org_id": schema.StringAttribute{
							Computed: true,
						},
						"prefix": schema.StringAttribute{
							Computed: true,
						},
						"revoked": schema.BoolAttribute{
							Computed: true,
						},
						"scope": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
						"user_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: OrgApiKeysType{
						ObjectType: types.ObjectType{
							AttrTypes: OrgApiKeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type OrgApiKeysModel struct {
	Id         types.String `tfsdk:"id"`
	OrgApiKeys types.Set    `tfsdk:"org_api_keys"`
}

var _ basetypes.ObjectTypable = OrgApiKeysType{}

type OrgApiKeysType struct {
	basetypes.ObjectType
}

func (t OrgApiKeysType) Equal(o attr.Type) bool {
	other, ok := o.(OrgApiKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OrgApiKeysType) String() string {
	return "OrgApiKeysType"
}

func (t OrgApiKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	expiresAtAttribute, ok := attributes["expires_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expires_at is missing from object`)

		return nil, diags
	}

	expiresAtVal, ok := expiresAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expires_at expected to be basetypes.StringValue, was: %T`, expiresAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUsedAtAttribute, ok := attributes["last_used_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_used_at is missing from object`)

		return nil, diags
	}

	lastUsedAtVal, ok := lastUsedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_used_at expected to be basetypes.StringValue, was: %T`, lastUsedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return nil, diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	prefixAttribute, ok := attributes["prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`prefix is missing from object`)

		return nil, diags
	}

	prefixVal, ok := prefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`prefix expected to be basetypes.StringValue, was: %T`, prefixAttribute))
	}

	revokedAttribute, ok := attributes["revoked"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`revoked is missing from object`)

		return nil, diags
	}

	revokedVal, ok := revokedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`revoked expected to be basetypes.BoolValue, was: %T`, revokedAttribute))
	}

	scopeAttribute, ok := attributes["scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope is missing from object`)

		return nil, diags
	}

	scopeVal, ok := scopeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope expected to be basetypes.StringValue, was: %T`, scopeAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OrgApiKeysValue{
		CreatedAt:  createdAtVal,
		ExpiresAt:  expiresAtVal,
		Id:         idVal,
		LastUsedAt: lastUsedAtVal,
		Name:       nameVal,
		OrgId:      orgIdVal,
		Prefix:     prefixVal,
		Revoked:    revokedVal,
		Scope:      scopeVal,
		UpdatedAt:  updatedAtVal,
		UserId:     userIdVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewOrgApiKeysValueNull() OrgApiKeysValue {
	return OrgApiKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewOrgApiKeysValueUnknown() OrgApiKeysValue {
	return OrgApiKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOrgApiKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OrgApiKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OrgApiKeysValue Attribute Value",
				"While creating a OrgApiKeysValue value, a missing attribute value was detected. "+
					"A OrgApiKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrgApiKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OrgApiKeysValue Attribute Type",
				"While creating a OrgApiKeysValue value, an invalid attribute value was detected. "+
					"A OrgApiKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrgApiKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OrgApiKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OrgApiKeysValue Attribute Value",
				"While creating a OrgApiKeysValue value, an extra attribute value was detected. "+
					"A OrgApiKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OrgApiKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOrgApiKeysValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	expiresAtAttribute, ok := attributes["expires_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expires_at is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	expiresAtVal, ok := expiresAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expires_at expected to be basetypes.StringValue, was: %T`, expiresAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUsedAtAttribute, ok := attributes["last_used_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_used_at is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	lastUsedAtVal, ok := lastUsedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_used_at expected to be basetypes.StringValue, was: %T`, lastUsedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	prefixAttribute, ok := attributes["prefix"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`prefix is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	prefixVal, ok := prefixAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`prefix expected to be basetypes.StringValue, was: %T`, prefixAttribute))
	}

	revokedAttribute, ok := attributes["revoked"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`revoked is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	revokedVal, ok := revokedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`revoked expected to be basetypes.BoolValue, was: %T`, revokedAttribute))
	}

	scopeAttribute, ok := attributes["scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	scopeVal, ok := scopeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope expected to be basetypes.StringValue, was: %T`, scopeAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return NewOrgApiKeysValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return NewOrgApiKeysValueUnknown(), diags
	}

	return OrgApiKeysValue{
		CreatedAt:  createdAtVal,
		ExpiresAt:  expiresAtVal,
		Id:         idVal,
		LastUsedAt: lastUsedAtVal,
		Name:       nameVal,
		OrgId:      orgIdVal,
		Prefix:     prefixVal,
		Revoked:    revokedVal,
		Scope:      scopeVal,
		UpdatedAt:  updatedAtVal,
		UserId:     userIdVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewOrgApiKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OrgApiKeysValue {
	object, diags := NewOrgApiKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOrgApiKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OrgApiKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOrgApiKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOrgApiKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOrgApiKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOrgApiKeysValueMust(OrgApiKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OrgApiKeysType) ValueType(ctx context.Context) attr.Value {
	return OrgApiKeysValue{}
}

var _ basetypes.ObjectValuable = OrgApiKeysValue{}

type OrgApiKeysValue struct {
	CreatedAt  basetypes.StringValue `tfsdk:"created_at"`
	ExpiresAt  basetypes.StringValue `tfsdk:"expires_at"`
	Id         basetypes.StringValue `tfsdk:"id"`
	LastUsedAt basetypes.StringValue `tfsdk:"last_used_at"`
	Name       basetypes.StringValue `tfsdk:"name"`
	OrgId      basetypes.StringValue `tfsdk:"org_id"`
	Prefix     basetypes.StringValue `tfsdk:"prefix"`
	Revoked    basetypes.BoolValue   `tfsdk:"revoked"`
	Scope      basetypes.StringValue `tfsdk:"scope"`
	UpdatedAt  basetypes.StringValue `tfsdk:"updated_at"`
	UserId     basetypes.StringValue `tfsdk:"user_id"`
	state      attr.ValueState
}

func (v OrgApiKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["expires_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_used_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["org_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["prefix"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["revoked"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["scope"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.ExpiresAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expires_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.LastUsedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_used_at"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OrgId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["org_id"] = val

		val, err = v.Prefix.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["prefix"] = val

		val, err = v.Revoked.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["revoked"] = val

		val, err = v.Scope.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scope"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OrgApiKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OrgApiKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OrgApiKeysValue) String() string {
	return "OrgApiKeysValue"
}

func (v OrgApiKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":   basetypes.StringType{},
		"expires_at":   basetypes.StringType{},
		"id":           basetypes.StringType{},
		"last_used_at": basetypes.StringType{},
		"name":         basetypes.StringType{},
		"org_id":       basetypes.StringType{},
		"prefix":       basetypes.StringType{},
		"revoked":      basetypes.BoolType{},
		"scope":        basetypes.StringType{},
		"updated_at":   basetypes.StringType{},
		"user_id":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":   v.CreatedAt,
			"expires_at":   v.ExpiresAt,
			"id":           v.Id,
			"last_used_at": v.LastUsedAt,
			"name":         v.Name,
			"org_id":       v.OrgId,
			"prefix":       v.Prefix,
			"revoked":      v.Revoked,
			"scope":        v.Scope,
			"updated_at":   v.UpdatedAt,
			"user_id":      v.UserId,
		})

	return objVal, diags
}

func (v OrgApiKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(OrgApiKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.ExpiresAt.Equal(other.ExpiresAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.LastUsedAt.Equal(other.LastUsedAt) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OrgId.Equal(other.OrgId) {
		return false
	}

	if !v.Prefix.Equal(other.Prefix) {
		return false
	}

	if !v.Revoked.Equal(other.Revoked) {
		return false
	}

	if !v.Scope.Equal(other.Scope) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v OrgApiKeysValue) Type(ctx context.Context) attr.Type {
	return OrgApiKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OrgApiKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":   basetypes.StringType{},
		"expires_at":   basetypes.StringType{},
		"id":           basetypes.StringType{},
		"last_used_at": basetypes.StringType{},
		"name":         basetypes.StringType{},
		"org_id":       basetypes.StringType{},
		"prefix":       basetypes.StringType{},
		"revoked":      basetypes.BoolType{},
		"scope":        basetypes.StringType{},
		"updated_at":   basetypes.StringType{},
		"user_id":      basetypes.StringType{},
	}
}
