// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_server

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"hostname": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Server ID (UUID)",
				MarkdownDescription: "Server ID (UUID)",
			},
			"organization_id": schema.StringAttribute{
				Computed: true,
			},
			"private_ip_address": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"public_ip_address": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"role": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"master",
						"worker",
						"bastion",
					),
				},
			},
			"ssh_key_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"ssh_user": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"status": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"pending",
						"provisioning",
						"ready",
						"failed",
					),
				},
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ServerModel struct {
	CreatedAt        types.String `tfsdk:"created_at"`
	Hostname         types.String `tfsdk:"hostname"`
	Id               types.String `tfsdk:"id"`
	OrganizationId   types.String `tfsdk:"organization_id"`
	PrivateIpAddress types.String `tfsdk:"private_ip_address"`
	PublicIpAddress  types.String `tfsdk:"public_ip_address"`
	Role             types.String `tfsdk:"role"`
	SshKeyId         types.String `tfsdk:"ssh_key_id"`
	SshUser          types.String `tfsdk:"ssh_user"`
	Status           types.String `tfsdk:"status"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
}
