// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_credential

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CredentialResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(32),
				},
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"credential_provider": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"aws",
						"cloudflare",
						"hetzner",
						"digitalocean",
						"generic",
					),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Credential ID (UUID)",
				MarkdownDescription: "Credential ID (UUID)",
			},
			"kind": schema.StringAttribute{
				Required:            true,
				Description:         "aws_access_key, api_token, basic_auth, oauth2",
				MarkdownDescription: "aws_access_key, api_token, basic_auth, oauth2",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "human label",
				MarkdownDescription: "human label",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(100),
				},
			},
			"region": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(32),
				},
			},
			"schema_version": schema.Int64Attribute{
				Required:            true,
				Description:         "secret schema version",
				MarkdownDescription: "secret schema version",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"scope": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				CustomType: ScopeType{
					ObjectType: types.ObjectType{
						AttrTypes: ScopeValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "{\"service\":\"route53\"} or {\"arn\":\"...\"}",
				MarkdownDescription: "{\"service\":\"route53\"} or {\"arn\":\"...\"}",
			},
			"scope_kind": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"credential_provider",
						"service",
						"resource",
					),
				},
			},
			"scope_version": schema.Int64Attribute{
				Required:            true,
				Description:         "scope schema version",
				MarkdownDescription: "scope schema version",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"secret": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				CustomType: SecretType{
					ObjectType: types.ObjectType{
						AttrTypes: SecretValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "encrypted later",
				MarkdownDescription: "encrypted later",
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type CredentialModel struct {
	AccountId          types.String `tfsdk:"account_id"`
	CreatedAt          types.String `tfsdk:"created_at"`
	CredentialProvider types.String `tfsdk:"credential_provider"`
	Id                 types.String `tfsdk:"id"`
	Kind               types.String `tfsdk:"kind"`
	Name               types.String `tfsdk:"name"`
	Region             types.String `tfsdk:"region"`
	SchemaVersion      types.Int64  `tfsdk:"schema_version"`
	Scope              ScopeValue   `tfsdk:"scope"`
	ScopeKind          types.String `tfsdk:"scope_kind"`
	ScopeVersion       types.Int64  `tfsdk:"scope_version"`
	Secret             SecretValue  `tfsdk:"secret"`
	UpdatedAt          types.String `tfsdk:"updated_at"`
}

var _ basetypes.ObjectTypable = ScopeType{}

type ScopeType struct {
	basetypes.ObjectType
}

func (t ScopeType) Equal(o attr.Type) bool {
	other, ok := o.(ScopeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScopeType) String() string {
	return "ScopeType"
}

func (t ScopeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return ScopeValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewScopeValueNull() ScopeValue {
	return ScopeValue{
		state: attr.ValueStateNull,
	}
}

func NewScopeValueUnknown() ScopeValue {
	return ScopeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScopeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScopeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScopeValue Attribute Value",
				"While creating a ScopeValue value, a missing attribute value was detected. "+
					"A ScopeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScopeValue Attribute Type",
				"While creating a ScopeValue value, an invalid attribute value was detected. "+
					"A ScopeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScopeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScopeValue Attribute Value",
				"While creating a ScopeValue value, an extra attribute value was detected. "+
					"A ScopeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScopeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScopeValueUnknown(), diags
	}

	if diags.HasError() {
		return NewScopeValueUnknown(), diags
	}

	return ScopeValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewScopeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScopeValue {
	object, diags := NewScopeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScopeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScopeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScopeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScopeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScopeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScopeValueMust(ScopeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScopeType) ValueType(ctx context.Context) attr.Value {
	return ScopeValue{}
}

var _ basetypes.ObjectValuable = ScopeValue{}

type ScopeValue struct {
	state attr.ValueState
}

func (v ScopeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScopeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScopeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScopeValue) String() string {
	return "ScopeValue"
}

func (v ScopeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v ScopeValue) Equal(o attr.Value) bool {
	other, ok := o.(ScopeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v ScopeValue) Type(ctx context.Context) attr.Type {
	return ScopeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScopeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}

var _ basetypes.ObjectTypable = SecretType{}

type SecretType struct {
	basetypes.ObjectType
}

func (t SecretType) Equal(o attr.Type) bool {
	other, ok := o.(SecretType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SecretType) String() string {
	return "SecretType"
}

func (t SecretType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return SecretValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewSecretValueNull() SecretValue {
	return SecretValue{
		state: attr.ValueStateNull,
	}
}

func NewSecretValueUnknown() SecretValue {
	return SecretValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSecretValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SecretValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SecretValue Attribute Value",
				"While creating a SecretValue value, a missing attribute value was detected. "+
					"A SecretValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SecretValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SecretValue Attribute Type",
				"While creating a SecretValue value, an invalid attribute value was detected. "+
					"A SecretValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SecretValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SecretValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SecretValue Attribute Value",
				"While creating a SecretValue value, an extra attribute value was detected. "+
					"A SecretValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SecretValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSecretValueUnknown(), diags
	}

	if diags.HasError() {
		return NewSecretValueUnknown(), diags
	}

	return SecretValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewSecretValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SecretValue {
	object, diags := NewSecretValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSecretValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SecretType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSecretValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSecretValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSecretValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSecretValueMust(SecretValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SecretType) ValueType(ctx context.Context) attr.Value {
	return SecretValue{}
}

var _ basetypes.ObjectValuable = SecretValue{}

type SecretValue struct {
	state attr.ValueState
}

func (v SecretValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SecretValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SecretValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SecretValue) String() string {
	return "SecretValue"
}

func (v SecretValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v SecretValue) Equal(o attr.Value) bool {
	other, ok := o.(SecretValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v SecretValue) Type(ctx context.Context) attr.Type {
	return SecretType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SecretValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
