// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_org

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrgResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"domain": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
				MarkdownDescription: "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type OrgModel struct {
	CreatedAt types.String `tfsdk:"created_at"`
	Domain    types.String `tfsdk:"domain"`
	Id        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	UpdatedAt types.String `tfsdk:"updated_at"`
}
