// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_ssh_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SshKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bits": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Only for RSA",
				MarkdownDescription: "Only for RSA",
			},
			"comment": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"fingerprint": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "SSH Key ID (UUID)",
				MarkdownDescription: "SSH Key ID (UUID)",
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"organization_id": schema.StringAttribute{
				Computed: true,
			},
			"public_key": schema.StringAttribute{
				Computed: true,
			},
			"reveal": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reveal private key PEM",
				MarkdownDescription: "Reveal private key PEM",
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "\"rsa\" (default) or \"ed25519\"",
				MarkdownDescription: "\"rsa\" (default) or \"ed25519\"",
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type SshKeyModel struct {
	Bits           types.Int64  `tfsdk:"bits"`
	Comment        types.String `tfsdk:"comment"`
	CreatedAt      types.String `tfsdk:"created_at"`
	Fingerprint    types.String `tfsdk:"fingerprint"`
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	OrganizationId types.String `tfsdk:"organization_id"`
	PublicKey      types.String `tfsdk:"public_key"`
	Reveal         types.Bool   `tfsdk:"reveal"`
	Type           types.String `tfsdk:"type"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
}
