// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_healthz

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func HealthzDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"status": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type HealthzModel struct {
	Status types.String `tfsdk:"status"`
}
