// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ssh_key_download

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SshKeyDownloadDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "SSH Key ID (UUID)",
				MarkdownDescription: "SSH Key ID (UUID)",
			},
			"part": schema.StringAttribute{
				Required:            true,
				Description:         "Which part to download",
				MarkdownDescription: "Which part to download",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"public",
						"private",
						"both",
					),
				},
			},
		},
	}
}

type SshKeyDownloadModel struct {
	Id   types.String `tfsdk:"id"`
	Part types.String `tfsdk:"part"`
}
