// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_node_pool_labels

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func NodePoolLabelsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Label Pool ID (UUID)",
				MarkdownDescription: "Label Pool ID (UUID)",
			},
			"node_pool_labels": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"key": schema.StringAttribute{
							Computed: true,
						},
						"organization_id": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
						"value": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: NodePoolLabelsType{
						ObjectType: types.ObjectType{
							AttrTypes: NodePoolLabelsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type NodePoolLabelsModel struct {
	Id             types.String `tfsdk:"id"`
	NodePoolLabels types.Set    `tfsdk:"node_pool_labels"`
}

var _ basetypes.ObjectTypable = NodePoolLabelsType{}

type NodePoolLabelsType struct {
	basetypes.ObjectType
}

func (t NodePoolLabelsType) Equal(o attr.Type) bool {
	other, ok := o.(NodePoolLabelsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodePoolLabelsType) String() string {
	return "NodePoolLabelsType"
}

func (t NodePoolLabelsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	organizationIdAttribute, ok := attributes["organization_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization_id is missing from object`)

		return nil, diags
	}

	organizationIdVal, ok := organizationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization_id expected to be basetypes.StringValue, was: %T`, organizationIdAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodePoolLabelsValue{
		CreatedAt:      createdAtVal,
		Id:             idVal,
		Key:            keyVal,
		OrganizationId: organizationIdVal,
		UpdatedAt:      updatedAtVal,
		Value:          valueVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewNodePoolLabelsValueNull() NodePoolLabelsValue {
	return NodePoolLabelsValue{
		state: attr.ValueStateNull,
	}
}

func NewNodePoolLabelsValueUnknown() NodePoolLabelsValue {
	return NodePoolLabelsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodePoolLabelsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodePoolLabelsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodePoolLabelsValue Attribute Value",
				"While creating a NodePoolLabelsValue value, a missing attribute value was detected. "+
					"A NodePoolLabelsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodePoolLabelsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodePoolLabelsValue Attribute Type",
				"While creating a NodePoolLabelsValue value, an invalid attribute value was detected. "+
					"A NodePoolLabelsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodePoolLabelsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodePoolLabelsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodePoolLabelsValue Attribute Value",
				"While creating a NodePoolLabelsValue value, an extra attribute value was detected. "+
					"A NodePoolLabelsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodePoolLabelsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodePoolLabelsValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewNodePoolLabelsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNodePoolLabelsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewNodePoolLabelsValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	organizationIdAttribute, ok := attributes["organization_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization_id is missing from object`)

		return NewNodePoolLabelsValueUnknown(), diags
	}

	organizationIdVal, ok := organizationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization_id expected to be basetypes.StringValue, was: %T`, organizationIdAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewNodePoolLabelsValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewNodePoolLabelsValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewNodePoolLabelsValueUnknown(), diags
	}

	return NodePoolLabelsValue{
		CreatedAt:      createdAtVal,
		Id:             idVal,
		Key:            keyVal,
		OrganizationId: organizationIdVal,
		UpdatedAt:      updatedAtVal,
		Value:          valueVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewNodePoolLabelsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodePoolLabelsValue {
	object, diags := NewNodePoolLabelsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodePoolLabelsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodePoolLabelsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodePoolLabelsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodePoolLabelsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodePoolLabelsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodePoolLabelsValueMust(NodePoolLabelsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodePoolLabelsType) ValueType(ctx context.Context) attr.Value {
	return NodePoolLabelsValue{}
}

var _ basetypes.ObjectValuable = NodePoolLabelsValue{}

type NodePoolLabelsValue struct {
	CreatedAt      basetypes.StringValue `tfsdk:"created_at"`
	Id             basetypes.StringValue `tfsdk:"id"`
	Key            basetypes.StringValue `tfsdk:"key"`
	OrganizationId basetypes.StringValue `tfsdk:"organization_id"`
	UpdatedAt      basetypes.StringValue `tfsdk:"updated_at"`
	Value          basetypes.StringValue `tfsdk:"value"`
	state          attr.ValueState
}

func (v NodePoolLabelsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["organization_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.OrganizationId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["organization_id"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodePoolLabelsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodePoolLabelsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodePoolLabelsValue) String() string {
	return "NodePoolLabelsValue"
}

func (v NodePoolLabelsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":      basetypes.StringType{},
		"id":              basetypes.StringType{},
		"key":             basetypes.StringType{},
		"organization_id": basetypes.StringType{},
		"updated_at":      basetypes.StringType{},
		"value":           basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":      v.CreatedAt,
			"id":              v.Id,
			"key":             v.Key,
			"organization_id": v.OrganizationId,
			"updated_at":      v.UpdatedAt,
			"value":           v.Value,
		})

	return objVal, diags
}

func (v NodePoolLabelsValue) Equal(o attr.Value) bool {
	other, ok := o.(NodePoolLabelsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.OrganizationId.Equal(other.OrganizationId) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v NodePoolLabelsValue) Type(ctx context.Context) attr.Type {
	return NodePoolLabelsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodePoolLabelsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":      basetypes.StringType{},
		"id":              basetypes.StringType{},
		"key":             basetypes.StringType{},
		"organization_id": basetypes.StringType{},
		"updated_at":      basetypes.StringType{},
		"value":           basetypes.StringType{},
	}
}
