// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_jwks

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func JwksDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"keys": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"alg": schema.StringAttribute{
							Computed: true,
						},
						"e": schema.StringAttribute{
							Computed: true,
						},
						"kid": schema.StringAttribute{
							Computed: true,
						},
						"kty": schema.StringAttribute{
							Computed: true,
						},
						"n": schema.StringAttribute{
							Computed: true,
						},
						"use": schema.StringAttribute{
							Computed: true,
						},
						"x": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: KeysType{
						ObjectType: types.ObjectType{
							AttrTypes: KeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type JwksModel struct {
	Keys types.List `tfsdk:"keys"`
}

var _ basetypes.ObjectTypable = KeysType{}

type KeysType struct {
	basetypes.ObjectType
}

func (t KeysType) Equal(o attr.Type) bool {
	other, ok := o.(KeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t KeysType) String() string {
	return "KeysType"
}

func (t KeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	algAttribute, ok := attributes["alg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alg is missing from object`)

		return nil, diags
	}

	algVal, ok := algAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alg expected to be basetypes.StringValue, was: %T`, algAttribute))
	}

	eAttribute, ok := attributes["e"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`e is missing from object`)

		return nil, diags
	}

	eVal, ok := eAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`e expected to be basetypes.StringValue, was: %T`, eAttribute))
	}

	kidAttribute, ok := attributes["kid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kid is missing from object`)

		return nil, diags
	}

	kidVal, ok := kidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kid expected to be basetypes.StringValue, was: %T`, kidAttribute))
	}

	ktyAttribute, ok := attributes["kty"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kty is missing from object`)

		return nil, diags
	}

	ktyVal, ok := ktyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kty expected to be basetypes.StringValue, was: %T`, ktyAttribute))
	}

	nAttribute, ok := attributes["n"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`n is missing from object`)

		return nil, diags
	}

	nVal, ok := nAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`n expected to be basetypes.StringValue, was: %T`, nAttribute))
	}

	useAttribute, ok := attributes["use"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use is missing from object`)

		return nil, diags
	}

	useVal, ok := useAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use expected to be basetypes.StringValue, was: %T`, useAttribute))
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return nil, diags
	}

	xVal, ok := xAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be basetypes.StringValue, was: %T`, xAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return KeysValue{
		Alg:   algVal,
		E:     eVal,
		Kid:   kidVal,
		Kty:   ktyVal,
		N:     nVal,
		Use:   useVal,
		X:     xVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewKeysValueNull() KeysValue {
	return KeysValue{
		state: attr.ValueStateNull,
	}
}

func NewKeysValueUnknown() KeysValue {
	return KeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (KeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing KeysValue Attribute Value",
				"While creating a KeysValue value, a missing attribute value was detected. "+
					"A KeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid KeysValue Attribute Type",
				"While creating a KeysValue value, an invalid attribute value was detected. "+
					"A KeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("KeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("KeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra KeysValue Attribute Value",
				"While creating a KeysValue value, an extra attribute value was detected. "+
					"A KeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra KeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	algAttribute, ok := attributes["alg"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alg is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	algVal, ok := algAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alg expected to be basetypes.StringValue, was: %T`, algAttribute))
	}

	eAttribute, ok := attributes["e"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`e is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	eVal, ok := eAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`e expected to be basetypes.StringValue, was: %T`, eAttribute))
	}

	kidAttribute, ok := attributes["kid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kid is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	kidVal, ok := kidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kid expected to be basetypes.StringValue, was: %T`, kidAttribute))
	}

	ktyAttribute, ok := attributes["kty"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kty is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	ktyVal, ok := ktyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kty expected to be basetypes.StringValue, was: %T`, ktyAttribute))
	}

	nAttribute, ok := attributes["n"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`n is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	nVal, ok := nAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`n expected to be basetypes.StringValue, was: %T`, nAttribute))
	}

	useAttribute, ok := attributes["use"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	useVal, ok := useAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use expected to be basetypes.StringValue, was: %T`, useAttribute))
	}

	xAttribute, ok := attributes["x"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`x is missing from object`)

		return NewKeysValueUnknown(), diags
	}

	xVal, ok := xAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`x expected to be basetypes.StringValue, was: %T`, xAttribute))
	}

	if diags.HasError() {
		return NewKeysValueUnknown(), diags
	}

	return KeysValue{
		Alg:   algVal,
		E:     eVal,
		Kid:   kidVal,
		Kty:   ktyVal,
		N:     nVal,
		Use:   useVal,
		X:     xVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) KeysValue {
	object, diags := NewKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t KeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewKeysValueMust(KeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t KeysType) ValueType(ctx context.Context) attr.Value {
	return KeysValue{}
}

var _ basetypes.ObjectValuable = KeysValue{}

type KeysValue struct {
	Alg   basetypes.StringValue `tfsdk:"alg"`
	E     basetypes.StringValue `tfsdk:"e"`
	Kid   basetypes.StringValue `tfsdk:"kid"`
	Kty   basetypes.StringValue `tfsdk:"kty"`
	N     basetypes.StringValue `tfsdk:"n"`
	Use   basetypes.StringValue `tfsdk:"use"`
	X     basetypes.StringValue `tfsdk:"x"`
	state attr.ValueState
}

func (v KeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["alg"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["e"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kid"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kty"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["n"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["use"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["x"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.Alg.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alg"] = val

		val, err = v.E.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["e"] = val

		val, err = v.Kid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kid"] = val

		val, err = v.Kty.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kty"] = val

		val, err = v.N.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["n"] = val

		val, err = v.Use.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["use"] = val

		val, err = v.X.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["x"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v KeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v KeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v KeysValue) String() string {
	return "KeysValue"
}

func (v KeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"alg": basetypes.StringType{},
		"e":   basetypes.StringType{},
		"kid": basetypes.StringType{},
		"kty": basetypes.StringType{},
		"n":   basetypes.StringType{},
		"use": basetypes.StringType{},
		"x":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"alg": v.Alg,
			"e":   v.E,
			"kid": v.Kid,
			"kty": v.Kty,
			"n":   v.N,
			"use": v.Use,
			"x":   v.X,
		})

	return objVal, diags
}

func (v KeysValue) Equal(o attr.Value) bool {
	other, ok := o.(KeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Alg.Equal(other.Alg) {
		return false
	}

	if !v.E.Equal(other.E) {
		return false
	}

	if !v.Kid.Equal(other.Kid) {
		return false
	}

	if !v.Kty.Equal(other.Kty) {
		return false
	}

	if !v.N.Equal(other.N) {
		return false
	}

	if !v.Use.Equal(other.Use) {
		return false
	}

	if !v.X.Equal(other.X) {
		return false
	}

	return true
}

func (v KeysValue) Type(ctx context.Context) attr.Type {
	return KeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v KeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alg": basetypes.StringType{},
		"e":   basetypes.StringType{},
		"kid": basetypes.StringType{},
		"kty": basetypes.StringType{},
		"n":   basetypes.StringType{},
		"use": basetypes.StringType{},
		"x":   basetypes.StringType{},
	}
}
