// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_load_balancers

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func LoadBalancersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"load_balancers": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"kind": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"organization_id": schema.StringAttribute{
							Computed: true,
						},
						"private_ip_address": schema.StringAttribute{
							Computed: true,
						},
						"public_ip_address": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: LoadBalancersType{
						ObjectType: types.ObjectType{
							AttrTypes: LoadBalancersValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type LoadBalancersModel struct {
	LoadBalancers types.Set `tfsdk:"load_balancers"`
}

var _ basetypes.ObjectTypable = LoadBalancersType{}

type LoadBalancersType struct {
	basetypes.ObjectType
}

func (t LoadBalancersType) Equal(o attr.Type) bool {
	other, ok := o.(LoadBalancersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LoadBalancersType) String() string {
	return "LoadBalancersType"
}

func (t LoadBalancersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return nil, diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	organizationIdAttribute, ok := attributes["organization_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization_id is missing from object`)

		return nil, diags
	}

	organizationIdVal, ok := organizationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization_id expected to be basetypes.StringValue, was: %T`, organizationIdAttribute))
	}

	privateIpAddressAttribute, ok := attributes["private_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`private_ip_address is missing from object`)

		return nil, diags
	}

	privateIpAddressVal, ok := privateIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`private_ip_address expected to be basetypes.StringValue, was: %T`, privateIpAddressAttribute))
	}

	publicIpAddressAttribute, ok := attributes["public_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`public_ip_address is missing from object`)

		return nil, diags
	}

	publicIpAddressVal, ok := publicIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`public_ip_address expected to be basetypes.StringValue, was: %T`, publicIpAddressAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LoadBalancersValue{
		CreatedAt:        createdAtVal,
		Id:               idVal,
		Kind:             kindVal,
		Name:             nameVal,
		OrganizationId:   organizationIdVal,
		PrivateIpAddress: privateIpAddressVal,
		PublicIpAddress:  publicIpAddressVal,
		UpdatedAt:        updatedAtVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewLoadBalancersValueNull() LoadBalancersValue {
	return LoadBalancersValue{
		state: attr.ValueStateNull,
	}
}

func NewLoadBalancersValueUnknown() LoadBalancersValue {
	return LoadBalancersValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLoadBalancersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LoadBalancersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LoadBalancersValue Attribute Value",
				"While creating a LoadBalancersValue value, a missing attribute value was detected. "+
					"A LoadBalancersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LoadBalancersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LoadBalancersValue Attribute Type",
				"While creating a LoadBalancersValue value, an invalid attribute value was detected. "+
					"A LoadBalancersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LoadBalancersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LoadBalancersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LoadBalancersValue Attribute Value",
				"While creating a LoadBalancersValue value, an extra attribute value was detected. "+
					"A LoadBalancersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LoadBalancersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLoadBalancersValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	organizationIdAttribute, ok := attributes["organization_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization_id is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	organizationIdVal, ok := organizationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization_id expected to be basetypes.StringValue, was: %T`, organizationIdAttribute))
	}

	privateIpAddressAttribute, ok := attributes["private_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`private_ip_address is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	privateIpAddressVal, ok := privateIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`private_ip_address expected to be basetypes.StringValue, was: %T`, privateIpAddressAttribute))
	}

	publicIpAddressAttribute, ok := attributes["public_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`public_ip_address is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	publicIpAddressVal, ok := publicIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`public_ip_address expected to be basetypes.StringValue, was: %T`, publicIpAddressAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewLoadBalancersValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewLoadBalancersValueUnknown(), diags
	}

	return LoadBalancersValue{
		CreatedAt:        createdAtVal,
		Id:               idVal,
		Kind:             kindVal,
		Name:             nameVal,
		OrganizationId:   organizationIdVal,
		PrivateIpAddress: privateIpAddressVal,
		PublicIpAddress:  publicIpAddressVal,
		UpdatedAt:        updatedAtVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewLoadBalancersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LoadBalancersValue {
	object, diags := NewLoadBalancersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLoadBalancersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LoadBalancersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLoadBalancersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLoadBalancersValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLoadBalancersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLoadBalancersValueMust(LoadBalancersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LoadBalancersType) ValueType(ctx context.Context) attr.Value {
	return LoadBalancersValue{}
}

var _ basetypes.ObjectValuable = LoadBalancersValue{}

type LoadBalancersValue struct {
	CreatedAt        basetypes.StringValue `tfsdk:"created_at"`
	Id               basetypes.StringValue `tfsdk:"id"`
	Kind             basetypes.StringValue `tfsdk:"kind"`
	Name             basetypes.StringValue `tfsdk:"name"`
	OrganizationId   basetypes.StringValue `tfsdk:"organization_id"`
	PrivateIpAddress basetypes.StringValue `tfsdk:"private_ip_address"`
	PublicIpAddress  basetypes.StringValue `tfsdk:"public_ip_address"`
	UpdatedAt        basetypes.StringValue `tfsdk:"updated_at"`
	state            attr.ValueState
}

func (v LoadBalancersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["organization_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["private_ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["public_ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Kind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kind"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OrganizationId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["organization_id"] = val

		val, err = v.PrivateIpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["private_ip_address"] = val

		val, err = v.PublicIpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["public_ip_address"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LoadBalancersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LoadBalancersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LoadBalancersValue) String() string {
	return "LoadBalancersValue"
}

func (v LoadBalancersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":         basetypes.StringType{},
		"id":                 basetypes.StringType{},
		"kind":               basetypes.StringType{},
		"name":               basetypes.StringType{},
		"organization_id":    basetypes.StringType{},
		"private_ip_address": basetypes.StringType{},
		"public_ip_address":  basetypes.StringType{},
		"updated_at":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":         v.CreatedAt,
			"id":                 v.Id,
			"kind":               v.Kind,
			"name":               v.Name,
			"organization_id":    v.OrganizationId,
			"private_ip_address": v.PrivateIpAddress,
			"public_ip_address":  v.PublicIpAddress,
			"updated_at":         v.UpdatedAt,
		})

	return objVal, diags
}

func (v LoadBalancersValue) Equal(o attr.Value) bool {
	other, ok := o.(LoadBalancersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Kind.Equal(other.Kind) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OrganizationId.Equal(other.OrganizationId) {
		return false
	}

	if !v.PrivateIpAddress.Equal(other.PrivateIpAddress) {
		return false
	}

	if !v.PublicIpAddress.Equal(other.PublicIpAddress) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v LoadBalancersValue) Type(ctx context.Context) attr.Type {
	return LoadBalancersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LoadBalancersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":         basetypes.StringType{},
		"id":                 basetypes.StringType{},
		"kind":               basetypes.StringType{},
		"name":               basetypes.StringType{},
		"organization_id":    basetypes.StringType{},
		"private_ip_address": basetypes.StringType{},
		"public_ip_address":  basetypes.StringType{},
		"updated_at":         basetypes.StringType{},
	}
}
