// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_org_member

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrgMemberResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Org ID (UUID)",
				MarkdownDescription: "Org ID (UUID)",
			},
			"role": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "owner/admin/member",
				MarkdownDescription: "owner/admin/member",
			},
			"user_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type OrgMemberModel struct {
	Email  types.String `tfsdk:"email"`
	Id     types.String `tfsdk:"id"`
	Role   types.String `tfsdk:"role"`
	UserId types.String `tfsdk:"user_id"`
}
