// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_me

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"avatar_url": schema.StringAttribute{
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"display_name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"emails": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"email": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
							MarkdownDescription: "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
						},
						"is_primary": schema.BoolAttribute{
							Computed: true,
						},
						"is_verified": schema.BoolAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
						"user": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"avatar_url": schema.StringAttribute{
									Computed: true,
								},
								"created_at": schema.StringAttribute{
									Computed: true,
								},
								"display_name": schema.StringAttribute{
									Computed: true,
								},
								"id": schema.StringAttribute{
									Computed:            true,
									Description:         "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
									MarkdownDescription: "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
								},
								"is_admin": schema.BoolAttribute{
									Computed: true,
								},
								"is_disabled": schema.BoolAttribute{
									Computed: true,
								},
								"primary_email": schema.StringAttribute{
									Computed: true,
								},
								"updated_at": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: UserType{
								ObjectType: types.ObjectType{
									AttrTypes: UserValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"user_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: EmailsType{
						ObjectType: types.ObjectType{
							AttrTypes: EmailsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
				MarkdownDescription: "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
			},
			"is_admin": schema.BoolAttribute{
				Computed: true,
			},
			"is_disabled": schema.BoolAttribute{
				Computed: true,
			},
			"organizations": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"domain": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
							MarkdownDescription: "example: 3fa85f64-5717-4562-b3fc-2c963f66afa6",
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: OrganizationsType{
						ObjectType: types.ObjectType{
							AttrTypes: OrganizationsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"primary_email": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type MeModel struct {
	AvatarUrl     types.String `tfsdk:"avatar_url"`
	CreatedAt     types.String `tfsdk:"created_at"`
	DisplayName   types.String `tfsdk:"display_name"`
	Emails        types.List   `tfsdk:"emails"`
	Id            types.String `tfsdk:"id"`
	IsAdmin       types.Bool   `tfsdk:"is_admin"`
	IsDisabled    types.Bool   `tfsdk:"is_disabled"`
	Organizations types.List   `tfsdk:"organizations"`
	PrimaryEmail  types.String `tfsdk:"primary_email"`
	UpdatedAt     types.String `tfsdk:"updated_at"`
}

var _ basetypes.ObjectTypable = EmailsType{}

type EmailsType struct {
	basetypes.ObjectType
}

func (t EmailsType) Equal(o attr.Type) bool {
	other, ok := o.(EmailsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t EmailsType) String() string {
	return "EmailsType"
}

func (t EmailsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return nil, diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isPrimaryAttribute, ok := attributes["is_primary"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_primary is missing from object`)

		return nil, diags
	}

	isPrimaryVal, ok := isPrimaryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_primary expected to be basetypes.BoolValue, was: %T`, isPrimaryAttribute))
	}

	isVerifiedAttribute, ok := attributes["is_verified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_verified is missing from object`)

		return nil, diags
	}

	isVerifiedVal, ok := isVerifiedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_verified expected to be basetypes.BoolValue, was: %T`, isVerifiedAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	userAttribute, ok := attributes["user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user is missing from object`)

		return nil, diags
	}

	userVal, ok := userAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user expected to be basetypes.ObjectValue, was: %T`, userAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return EmailsValue{
		CreatedAt:  createdAtVal,
		Email:      emailVal,
		Id:         idVal,
		IsPrimary:  isPrimaryVal,
		IsVerified: isVerifiedVal,
		UpdatedAt:  updatedAtVal,
		User:       userVal,
		UserId:     userIdVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewEmailsValueNull() EmailsValue {
	return EmailsValue{
		state: attr.ValueStateNull,
	}
}

func NewEmailsValueUnknown() EmailsValue {
	return EmailsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewEmailsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (EmailsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing EmailsValue Attribute Value",
				"While creating a EmailsValue value, a missing attribute value was detected. "+
					"A EmailsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EmailsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid EmailsValue Attribute Type",
				"While creating a EmailsValue value, an invalid attribute value was detected. "+
					"A EmailsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("EmailsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("EmailsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra EmailsValue Attribute Value",
				"While creating a EmailsValue value, an extra attribute value was detected. "+
					"A EmailsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra EmailsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewEmailsValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	emailAttribute, ok := attributes["email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	emailVal, ok := emailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email expected to be basetypes.StringValue, was: %T`, emailAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isPrimaryAttribute, ok := attributes["is_primary"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_primary is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	isPrimaryVal, ok := isPrimaryAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_primary expected to be basetypes.BoolValue, was: %T`, isPrimaryAttribute))
	}

	isVerifiedAttribute, ok := attributes["is_verified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_verified is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	isVerifiedVal, ok := isVerifiedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_verified expected to be basetypes.BoolValue, was: %T`, isVerifiedAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	userAttribute, ok := attributes["user"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	userVal, ok := userAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user expected to be basetypes.ObjectValue, was: %T`, userAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return NewEmailsValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return NewEmailsValueUnknown(), diags
	}

	return EmailsValue{
		CreatedAt:  createdAtVal,
		Email:      emailVal,
		Id:         idVal,
		IsPrimary:  isPrimaryVal,
		IsVerified: isVerifiedVal,
		UpdatedAt:  updatedAtVal,
		User:       userVal,
		UserId:     userIdVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewEmailsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) EmailsValue {
	object, diags := NewEmailsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewEmailsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t EmailsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewEmailsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewEmailsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewEmailsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewEmailsValueMust(EmailsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t EmailsType) ValueType(ctx context.Context) attr.Value {
	return EmailsValue{}
}

var _ basetypes.ObjectValuable = EmailsValue{}

type EmailsValue struct {
	CreatedAt  basetypes.StringValue `tfsdk:"created_at"`
	Email      basetypes.StringValue `tfsdk:"email"`
	Id         basetypes.StringValue `tfsdk:"id"`
	IsPrimary  basetypes.BoolValue   `tfsdk:"is_primary"`
	IsVerified basetypes.BoolValue   `tfsdk:"is_verified"`
	UpdatedAt  basetypes.StringValue `tfsdk:"updated_at"`
	User       basetypes.ObjectValue `tfsdk:"user"`
	UserId     basetypes.StringValue `tfsdk:"user_id"`
	state      attr.ValueState
}

func (v EmailsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_primary"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["is_verified"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user"] = basetypes.ObjectType{
		AttrTypes: UserValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Email.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.IsPrimary.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_primary"] = val

		val, err = v.IsVerified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_verified"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		val, err = v.User.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v EmailsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v EmailsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v EmailsValue) String() string {
	return "EmailsValue"
}

func (v EmailsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var user basetypes.ObjectValue

	if v.User.IsNull() {
		user = types.ObjectNull(
			UserValue{}.AttributeTypes(ctx),
		)
	}

	if v.User.IsUnknown() {
		user = types.ObjectUnknown(
			UserValue{}.AttributeTypes(ctx),
		)
	}

	if !v.User.IsNull() && !v.User.IsUnknown() {
		user = types.ObjectValueMust(
			UserValue{}.AttributeTypes(ctx),
			v.User.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"email":       basetypes.StringType{},
		"id":          basetypes.StringType{},
		"is_primary":  basetypes.BoolType{},
		"is_verified": basetypes.BoolType{},
		"updated_at":  basetypes.StringType{},
		"user": basetypes.ObjectType{
			AttrTypes: UserValue{}.AttributeTypes(ctx),
		},
		"user_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":  v.CreatedAt,
			"email":       v.Email,
			"id":          v.Id,
			"is_primary":  v.IsPrimary,
			"is_verified": v.IsVerified,
			"updated_at":  v.UpdatedAt,
			"user":        user,
			"user_id":     v.UserId,
		})

	return objVal, diags
}

func (v EmailsValue) Equal(o attr.Value) bool {
	other, ok := o.(EmailsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Email.Equal(other.Email) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.IsPrimary.Equal(other.IsPrimary) {
		return false
	}

	if !v.IsVerified.Equal(other.IsVerified) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	if !v.User.Equal(other.User) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v EmailsValue) Type(ctx context.Context) attr.Type {
	return EmailsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v EmailsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":  basetypes.StringType{},
		"email":       basetypes.StringType{},
		"id":          basetypes.StringType{},
		"is_primary":  basetypes.BoolType{},
		"is_verified": basetypes.BoolType{},
		"updated_at":  basetypes.StringType{},
		"user": basetypes.ObjectType{
			AttrTypes: UserValue{}.AttributeTypes(ctx),
		},
		"user_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = UserType{}

type UserType struct {
	basetypes.ObjectType
}

func (t UserType) Equal(o attr.Type) bool {
	other, ok := o.(UserType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserType) String() string {
	return "UserType"
}

func (t UserType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	avatarUrlAttribute, ok := attributes["avatar_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avatar_url is missing from object`)

		return nil, diags
	}

	avatarUrlVal, ok := avatarUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avatar_url expected to be basetypes.StringValue, was: %T`, avatarUrlAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	displayNameAttribute, ok := attributes["display_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display_name is missing from object`)

		return nil, diags
	}

	displayNameVal, ok := displayNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display_name expected to be basetypes.StringValue, was: %T`, displayNameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isAdminAttribute, ok := attributes["is_admin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_admin is missing from object`)

		return nil, diags
	}

	isAdminVal, ok := isAdminAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_admin expected to be basetypes.BoolValue, was: %T`, isAdminAttribute))
	}

	isDisabledAttribute, ok := attributes["is_disabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_disabled is missing from object`)

		return nil, diags
	}

	isDisabledVal, ok := isDisabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_disabled expected to be basetypes.BoolValue, was: %T`, isDisabledAttribute))
	}

	primaryEmailAttribute, ok := attributes["primary_email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`primary_email is missing from object`)

		return nil, diags
	}

	primaryEmailVal, ok := primaryEmailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`primary_email expected to be basetypes.StringValue, was: %T`, primaryEmailAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserValue{
		AvatarUrl:    avatarUrlVal,
		CreatedAt:    createdAtVal,
		DisplayName:  displayNameVal,
		Id:           idVal,
		IsAdmin:      isAdminVal,
		IsDisabled:   isDisabledVal,
		PrimaryEmail: primaryEmailVal,
		UpdatedAt:    updatedAtVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewUserValueNull() UserValue {
	return UserValue{
		state: attr.ValueStateNull,
	}
}

func NewUserValueUnknown() UserValue {
	return UserValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserValue Attribute Value",
				"While creating a UserValue value, a missing attribute value was detected. "+
					"A UserValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserValue Attribute Type",
				"While creating a UserValue value, an invalid attribute value was detected. "+
					"A UserValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserValue Attribute Value",
				"While creating a UserValue value, an extra attribute value was detected. "+
					"A UserValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	avatarUrlAttribute, ok := attributes["avatar_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avatar_url is missing from object`)

		return NewUserValueUnknown(), diags
	}

	avatarUrlVal, ok := avatarUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avatar_url expected to be basetypes.StringValue, was: %T`, avatarUrlAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewUserValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	displayNameAttribute, ok := attributes["display_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display_name is missing from object`)

		return NewUserValueUnknown(), diags
	}

	displayNameVal, ok := displayNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display_name expected to be basetypes.StringValue, was: %T`, displayNameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewUserValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	isAdminAttribute, ok := attributes["is_admin"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_admin is missing from object`)

		return NewUserValueUnknown(), diags
	}

	isAdminVal, ok := isAdminAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_admin expected to be basetypes.BoolValue, was: %T`, isAdminAttribute))
	}

	isDisabledAttribute, ok := attributes["is_disabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_disabled is missing from object`)

		return NewUserValueUnknown(), diags
	}

	isDisabledVal, ok := isDisabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_disabled expected to be basetypes.BoolValue, was: %T`, isDisabledAttribute))
	}

	primaryEmailAttribute, ok := attributes["primary_email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`primary_email is missing from object`)

		return NewUserValueUnknown(), diags
	}

	primaryEmailVal, ok := primaryEmailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`primary_email expected to be basetypes.StringValue, was: %T`, primaryEmailAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewUserValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewUserValueUnknown(), diags
	}

	return UserValue{
		AvatarUrl:    avatarUrlVal,
		CreatedAt:    createdAtVal,
		DisplayName:  displayNameVal,
		Id:           idVal,
		IsAdmin:      isAdminVal,
		IsDisabled:   isDisabledVal,
		PrimaryEmail: primaryEmailVal,
		UpdatedAt:    updatedAtVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewUserValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserValue {
	object, diags := NewUserValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserValueMust(UserValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserType) ValueType(ctx context.Context) attr.Value {
	return UserValue{}
}

var _ basetypes.ObjectValuable = UserValue{}

type UserValue struct {
	AvatarUrl    basetypes.StringValue `tfsdk:"avatar_url"`
	CreatedAt    basetypes.StringValue `tfsdk:"created_at"`
	DisplayName  basetypes.StringValue `tfsdk:"display_name"`
	Id           basetypes.StringValue `tfsdk:"id"`
	IsAdmin      basetypes.BoolValue   `tfsdk:"is_admin"`
	IsDisabled   basetypes.BoolValue   `tfsdk:"is_disabled"`
	PrimaryEmail basetypes.StringValue `tfsdk:"primary_email"`
	UpdatedAt    basetypes.StringValue `tfsdk:"updated_at"`
	state        attr.ValueState
}

func (v UserValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["avatar_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["display_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_admin"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["is_disabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["primary_email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.AvatarUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["avatar_url"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.DisplayName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["display_name"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.IsAdmin.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_admin"] = val

		val, err = v.IsDisabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_disabled"] = val

		val, err = v.PrimaryEmail.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["primary_email"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserValue) String() string {
	return "UserValue"
}

func (v UserValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"avatar_url":    basetypes.StringType{},
		"created_at":    basetypes.StringType{},
		"display_name":  basetypes.StringType{},
		"id":            basetypes.StringType{},
		"is_admin":      basetypes.BoolType{},
		"is_disabled":   basetypes.BoolType{},
		"primary_email": basetypes.StringType{},
		"updated_at":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"avatar_url":    v.AvatarUrl,
			"created_at":    v.CreatedAt,
			"display_name":  v.DisplayName,
			"id":            v.Id,
			"is_admin":      v.IsAdmin,
			"is_disabled":   v.IsDisabled,
			"primary_email": v.PrimaryEmail,
			"updated_at":    v.UpdatedAt,
		})

	return objVal, diags
}

func (v UserValue) Equal(o attr.Value) bool {
	other, ok := o.(UserValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AvatarUrl.Equal(other.AvatarUrl) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.DisplayName.Equal(other.DisplayName) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.IsAdmin.Equal(other.IsAdmin) {
		return false
	}

	if !v.IsDisabled.Equal(other.IsDisabled) {
		return false
	}

	if !v.PrimaryEmail.Equal(other.PrimaryEmail) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v UserValue) Type(ctx context.Context) attr.Type {
	return UserType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"avatar_url":    basetypes.StringType{},
		"created_at":    basetypes.StringType{},
		"display_name":  basetypes.StringType{},
		"id":            basetypes.StringType{},
		"is_admin":      basetypes.BoolType{},
		"is_disabled":   basetypes.BoolType{},
		"primary_email": basetypes.StringType{},
		"updated_at":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OrganizationsType{}

type OrganizationsType struct {
	basetypes.ObjectType
}

func (t OrganizationsType) Equal(o attr.Type) bool {
	other, ok := o.(OrganizationsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OrganizationsType) String() string {
	return "OrganizationsType"
}

func (t OrganizationsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	domainAttribute, ok := attributes["domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`domain is missing from object`)

		return nil, diags
	}

	domainVal, ok := domainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`domain expected to be basetypes.StringValue, was: %T`, domainAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OrganizationsValue{
		CreatedAt: createdAtVal,
		Domain:    domainVal,
		Id:        idVal,
		Name:      nameVal,
		UpdatedAt: updatedAtVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOrganizationsValueNull() OrganizationsValue {
	return OrganizationsValue{
		state: attr.ValueStateNull,
	}
}

func NewOrganizationsValueUnknown() OrganizationsValue {
	return OrganizationsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOrganizationsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OrganizationsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OrganizationsValue Attribute Value",
				"While creating a OrganizationsValue value, a missing attribute value was detected. "+
					"A OrganizationsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrganizationsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OrganizationsValue Attribute Type",
				"While creating a OrganizationsValue value, an invalid attribute value was detected. "+
					"A OrganizationsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OrganizationsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OrganizationsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OrganizationsValue Attribute Value",
				"While creating a OrganizationsValue value, an extra attribute value was detected. "+
					"A OrganizationsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OrganizationsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOrganizationsValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewOrganizationsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	domainAttribute, ok := attributes["domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`domain is missing from object`)

		return NewOrganizationsValueUnknown(), diags
	}

	domainVal, ok := domainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`domain expected to be basetypes.StringValue, was: %T`, domainAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOrganizationsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOrganizationsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewOrganizationsValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewOrganizationsValueUnknown(), diags
	}

	return OrganizationsValue{
		CreatedAt: createdAtVal,
		Domain:    domainVal,
		Id:        idVal,
		Name:      nameVal,
		UpdatedAt: updatedAtVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOrganizationsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OrganizationsValue {
	object, diags := NewOrganizationsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOrganizationsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OrganizationsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOrganizationsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOrganizationsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOrganizationsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOrganizationsValueMust(OrganizationsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OrganizationsType) ValueType(ctx context.Context) attr.Value {
	return OrganizationsValue{}
}

var _ basetypes.ObjectValuable = OrganizationsValue{}

type OrganizationsValue struct {
	CreatedAt basetypes.StringValue `tfsdk:"created_at"`
	Domain    basetypes.StringValue `tfsdk:"domain"`
	Id        basetypes.StringValue `tfsdk:"id"`
	Name      basetypes.StringValue `tfsdk:"name"`
	UpdatedAt basetypes.StringValue `tfsdk:"updated_at"`
	state     attr.ValueState
}

func (v OrganizationsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["domain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Domain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["domain"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OrganizationsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OrganizationsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OrganizationsValue) String() string {
	return "OrganizationsValue"
}

func (v OrganizationsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at": basetypes.StringType{},
		"domain":     basetypes.StringType{},
		"id":         basetypes.StringType{},
		"name":       basetypes.StringType{},
		"updated_at": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at": v.CreatedAt,
			"domain":     v.Domain,
			"id":         v.Id,
			"name":       v.Name,
			"updated_at": v.UpdatedAt,
		})

	return objVal, diags
}

func (v OrganizationsValue) Equal(o attr.Value) bool {
	other, ok := o.(OrganizationsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Domain.Equal(other.Domain) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v OrganizationsValue) Type(ctx context.Context) attr.Type {
	return OrganizationsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OrganizationsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at": basetypes.StringType{},
		"domain":     basetypes.StringType{},
		"id":         basetypes.StringType{},
		"name":       basetypes.StringType{},
		"updated_at": basetypes.StringType{},
	}
}
