// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_load_balancer

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LoadBalancerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "LoadBalancer ID (UUID)",
				MarkdownDescription: "LoadBalancer ID (UUID)",
			},
			"kind": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"glueops",
						"public",
					),
				},
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"organization_id": schema.StringAttribute{
				Computed: true,
			},
			"private_ip_address": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"public_ip_address": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type LoadBalancerModel struct {
	CreatedAt        types.String `tfsdk:"created_at"`
	Id               types.String `tfsdk:"id"`
	Kind             types.String `tfsdk:"kind"`
	Name             types.String `tfsdk:"name"`
	OrganizationId   types.String `tfsdk:"organization_id"`
	PrivateIpAddress types.String `tfsdk:"private_ip_address"`
	PublicIpAddress  types.String `tfsdk:"public_ip_address"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
}
