// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_autoglue

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func AutoglueProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type AutoglueModel struct {
}
