// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_taint

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TaintResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"effect": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Node Taint ID (UUID)",
				MarkdownDescription: "Node Taint ID (UUID)",
			},
			"key": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"organization_id": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"value": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type TaintModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	Effect         types.String `tfsdk:"effect"`
	Id             types.String `tfsdk:"id"`
	Key            types.String `tfsdk:"key"`
	OrganizationId types.String `tfsdk:"organization_id"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
	Value          types.String `tfsdk:"value"`
}
