// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_credentials

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"credential_provider": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by provider (e.g., aws)",
				MarkdownDescription: "Filter by provider (e.g., aws)",
			},
			"credentials": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"account_id": schema.StringAttribute{
							Computed: true,
						},
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"credential_provider": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"kind": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"region": schema.StringAttribute{
							Computed: true,
						},
						"schema_version": schema.Int64Attribute{
							Computed: true,
						},
						"scope": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{},
							CustomType: ScopeType{
								ObjectType: types.ObjectType{
									AttrTypes: ScopeValue{}.AttributeTypes(ctx),
								},
							},
							Computed: true,
						},
						"scope_kind": schema.StringAttribute{
							Computed: true,
						},
						"scope_version": schema.Int64Attribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: CredentialsType{
						ObjectType: types.ObjectType{
							AttrTypes: CredentialsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"kind": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by kind (e.g., aws_access_key)",
				MarkdownDescription: "Filter by kind (e.g., aws_access_key)",
			},
			"scope_kind": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by scope kind (credential_provider/service/resource)",
				MarkdownDescription: "Filter by scope kind (credential_provider/service/resource)",
			},
		},
	}
}

type CredentialsModel struct {
	CredentialProvider types.String `tfsdk:"credential_provider"`
	Credentials        types.Set    `tfsdk:"credentials"`
	Kind               types.String `tfsdk:"kind"`
	ScopeKind          types.String `tfsdk:"scope_kind"`
}

var _ basetypes.ObjectTypable = CredentialsType{}

type CredentialsType struct {
	basetypes.ObjectType
}

func (t CredentialsType) Equal(o attr.Type) bool {
	other, ok := o.(CredentialsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CredentialsType) String() string {
	return "CredentialsType"
}

func (t CredentialsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	accountIdAttribute, ok := attributes["account_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_id is missing from object`)

		return nil, diags
	}

	accountIdVal, ok := accountIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_id expected to be basetypes.StringValue, was: %T`, accountIdAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	credentialProviderAttribute, ok := attributes["credential_provider"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credential_provider is missing from object`)

		return nil, diags
	}

	credentialProviderVal, ok := credentialProviderAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credential_provider expected to be basetypes.StringValue, was: %T`, credentialProviderAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return nil, diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return nil, diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	schemaVersionAttribute, ok := attributes["schema_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`schema_version is missing from object`)

		return nil, diags
	}

	schemaVersionVal, ok := schemaVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`schema_version expected to be basetypes.Int64Value, was: %T`, schemaVersionAttribute))
	}

	scopeAttribute, ok := attributes["scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope is missing from object`)

		return nil, diags
	}

	scopeVal, ok := scopeAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope expected to be basetypes.ObjectValue, was: %T`, scopeAttribute))
	}

	scopeKindAttribute, ok := attributes["scope_kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope_kind is missing from object`)

		return nil, diags
	}

	scopeKindVal, ok := scopeKindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope_kind expected to be basetypes.StringValue, was: %T`, scopeKindAttribute))
	}

	scopeVersionAttribute, ok := attributes["scope_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope_version is missing from object`)

		return nil, diags
	}

	scopeVersionVal, ok := scopeVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope_version expected to be basetypes.Int64Value, was: %T`, scopeVersionAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CredentialsValue{
		AccountId:          accountIdVal,
		CreatedAt:          createdAtVal,
		CredentialProvider: credentialProviderVal,
		Id:                 idVal,
		Kind:               kindVal,
		Name:               nameVal,
		Region:             regionVal,
		SchemaVersion:      schemaVersionVal,
		Scope:              scopeVal,
		ScopeKind:          scopeKindVal,
		ScopeVersion:       scopeVersionVal,
		UpdatedAt:          updatedAtVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewCredentialsValueNull() CredentialsValue {
	return CredentialsValue{
		state: attr.ValueStateNull,
	}
}

func NewCredentialsValueUnknown() CredentialsValue {
	return CredentialsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCredentialsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CredentialsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CredentialsValue Attribute Value",
				"While creating a CredentialsValue value, a missing attribute value was detected. "+
					"A CredentialsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CredentialsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CredentialsValue Attribute Type",
				"While creating a CredentialsValue value, an invalid attribute value was detected. "+
					"A CredentialsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CredentialsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CredentialsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CredentialsValue Attribute Value",
				"While creating a CredentialsValue value, an extra attribute value was detected. "+
					"A CredentialsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CredentialsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCredentialsValueUnknown(), diags
	}

	accountIdAttribute, ok := attributes["account_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_id is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	accountIdVal, ok := accountIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_id expected to be basetypes.StringValue, was: %T`, accountIdAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	credentialProviderAttribute, ok := attributes["credential_provider"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credential_provider is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	credentialProviderVal, ok := credentialProviderAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credential_provider expected to be basetypes.StringValue, was: %T`, credentialProviderAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	kindAttribute, ok := attributes["kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`kind is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	kindVal, ok := kindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`kind expected to be basetypes.StringValue, was: %T`, kindAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	schemaVersionAttribute, ok := attributes["schema_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`schema_version is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	schemaVersionVal, ok := schemaVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`schema_version expected to be basetypes.Int64Value, was: %T`, schemaVersionAttribute))
	}

	scopeAttribute, ok := attributes["scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	scopeVal, ok := scopeAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope expected to be basetypes.ObjectValue, was: %T`, scopeAttribute))
	}

	scopeKindAttribute, ok := attributes["scope_kind"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope_kind is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	scopeKindVal, ok := scopeKindAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope_kind expected to be basetypes.StringValue, was: %T`, scopeKindAttribute))
	}

	scopeVersionAttribute, ok := attributes["scope_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope_version is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	scopeVersionVal, ok := scopeVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope_version expected to be basetypes.Int64Value, was: %T`, scopeVersionAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewCredentialsValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	if diags.HasError() {
		return NewCredentialsValueUnknown(), diags
	}

	return CredentialsValue{
		AccountId:          accountIdVal,
		CreatedAt:          createdAtVal,
		CredentialProvider: credentialProviderVal,
		Id:                 idVal,
		Kind:               kindVal,
		Name:               nameVal,
		Region:             regionVal,
		SchemaVersion:      schemaVersionVal,
		Scope:              scopeVal,
		ScopeKind:          scopeKindVal,
		ScopeVersion:       scopeVersionVal,
		UpdatedAt:          updatedAtVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewCredentialsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CredentialsValue {
	object, diags := NewCredentialsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCredentialsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CredentialsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCredentialsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCredentialsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCredentialsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCredentialsValueMust(CredentialsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CredentialsType) ValueType(ctx context.Context) attr.Value {
	return CredentialsValue{}
}

var _ basetypes.ObjectValuable = CredentialsValue{}

type CredentialsValue struct {
	AccountId          basetypes.StringValue `tfsdk:"account_id"`
	CreatedAt          basetypes.StringValue `tfsdk:"created_at"`
	CredentialProvider basetypes.StringValue `tfsdk:"credential_provider"`
	Id                 basetypes.StringValue `tfsdk:"id"`
	Kind               basetypes.StringValue `tfsdk:"kind"`
	Name               basetypes.StringValue `tfsdk:"name"`
	Region             basetypes.StringValue `tfsdk:"region"`
	SchemaVersion      basetypes.Int64Value  `tfsdk:"schema_version"`
	Scope              basetypes.ObjectValue `tfsdk:"scope"`
	ScopeKind          basetypes.StringValue `tfsdk:"scope_kind"`
	ScopeVersion       basetypes.Int64Value  `tfsdk:"scope_version"`
	UpdatedAt          basetypes.StringValue `tfsdk:"updated_at"`
	state              attr.ValueState
}

func (v CredentialsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["account_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["credential_provider"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["schema_version"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["scope"] = basetypes.ObjectType{
		AttrTypes: ScopeValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["scope_kind"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["scope_version"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.AccountId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["account_id"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CredentialProvider.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["credential_provider"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Kind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["kind"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Region.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region"] = val

		val, err = v.SchemaVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["schema_version"] = val

		val, err = v.Scope.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scope"] = val

		val, err = v.ScopeKind.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scope_kind"] = val

		val, err = v.ScopeVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scope_version"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CredentialsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CredentialsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CredentialsValue) String() string {
	return "CredentialsValue"
}

func (v CredentialsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var scope basetypes.ObjectValue

	if v.Scope.IsNull() {
		scope = types.ObjectNull(
			ScopeValue{}.AttributeTypes(ctx),
		)
	}

	if v.Scope.IsUnknown() {
		scope = types.ObjectUnknown(
			ScopeValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Scope.IsNull() && !v.Scope.IsUnknown() {
		scope = types.ObjectValueMust(
			ScopeValue{}.AttributeTypes(ctx),
			v.Scope.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"account_id":          basetypes.StringType{},
		"created_at":          basetypes.StringType{},
		"credential_provider": basetypes.StringType{},
		"id":                  basetypes.StringType{},
		"kind":                basetypes.StringType{},
		"name":                basetypes.StringType{},
		"region":              basetypes.StringType{},
		"schema_version":      basetypes.Int64Type{},
		"scope": basetypes.ObjectType{
			AttrTypes: ScopeValue{}.AttributeTypes(ctx),
		},
		"scope_kind":    basetypes.StringType{},
		"scope_version": basetypes.Int64Type{},
		"updated_at":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"account_id":          v.AccountId,
			"created_at":          v.CreatedAt,
			"credential_provider": v.CredentialProvider,
			"id":                  v.Id,
			"kind":                v.Kind,
			"name":                v.Name,
			"region":              v.Region,
			"schema_version":      v.SchemaVersion,
			"scope":               scope,
			"scope_kind":          v.ScopeKind,
			"scope_version":       v.ScopeVersion,
			"updated_at":          v.UpdatedAt,
		})

	return objVal, diags
}

func (v CredentialsValue) Equal(o attr.Value) bool {
	other, ok := o.(CredentialsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AccountId.Equal(other.AccountId) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CredentialProvider.Equal(other.CredentialProvider) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Kind.Equal(other.Kind) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Region.Equal(other.Region) {
		return false
	}

	if !v.SchemaVersion.Equal(other.SchemaVersion) {
		return false
	}

	if !v.Scope.Equal(other.Scope) {
		return false
	}

	if !v.ScopeKind.Equal(other.ScopeKind) {
		return false
	}

	if !v.ScopeVersion.Equal(other.ScopeVersion) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	return true
}

func (v CredentialsValue) Type(ctx context.Context) attr.Type {
	return CredentialsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CredentialsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"account_id":          basetypes.StringType{},
		"created_at":          basetypes.StringType{},
		"credential_provider": basetypes.StringType{},
		"id":                  basetypes.StringType{},
		"kind":                basetypes.StringType{},
		"name":                basetypes.StringType{},
		"region":              basetypes.StringType{},
		"schema_version":      basetypes.Int64Type{},
		"scope": basetypes.ObjectType{
			AttrTypes: ScopeValue{}.AttributeTypes(ctx),
		},
		"scope_kind":    basetypes.StringType{},
		"scope_version": basetypes.Int64Type{},
		"updated_at":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ScopeType{}

type ScopeType struct {
	basetypes.ObjectType
}

func (t ScopeType) Equal(o attr.Type) bool {
	other, ok := o.(ScopeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScopeType) String() string {
	return "ScopeType"
}

func (t ScopeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return ScopeValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewScopeValueNull() ScopeValue {
	return ScopeValue{
		state: attr.ValueStateNull,
	}
}

func NewScopeValueUnknown() ScopeValue {
	return ScopeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScopeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScopeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScopeValue Attribute Value",
				"While creating a ScopeValue value, a missing attribute value was detected. "+
					"A ScopeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScopeValue Attribute Type",
				"While creating a ScopeValue value, an invalid attribute value was detected. "+
					"A ScopeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScopeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScopeValue Attribute Value",
				"While creating a ScopeValue value, an extra attribute value was detected. "+
					"A ScopeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScopeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScopeValueUnknown(), diags
	}

	if diags.HasError() {
		return NewScopeValueUnknown(), diags
	}

	return ScopeValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewScopeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScopeValue {
	object, diags := NewScopeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScopeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScopeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScopeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScopeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScopeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScopeValueMust(ScopeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScopeType) ValueType(ctx context.Context) attr.Value {
	return ScopeValue{}
}

var _ basetypes.ObjectValuable = ScopeValue{}

type ScopeValue struct {
	state attr.ValueState
}

func (v ScopeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScopeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScopeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScopeValue) String() string {
	return "ScopeValue"
}

func (v ScopeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v ScopeValue) Equal(o attr.Value) bool {
	other, ok := o.(ScopeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v ScopeValue) Type(ctx context.Context) attr.Type {
	return ScopeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScopeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}
