// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_domain

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DomainResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"credential_id": schema.StringAttribute{
				Required: true,
			},
			"domain_name": schema.StringAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Domain ID (UUID)",
				MarkdownDescription: "Domain ID (UUID)",
			},
			"last_error": schema.StringAttribute{
				Computed: true,
			},
			"organization_id": schema.StringAttribute{
				Computed: true,
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"zone_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(128),
				},
			},
		},
	}
}

type DomainModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	CredentialId   types.String `tfsdk:"credential_id"`
	DomainName     types.String `tfsdk:"domain_name"`
	Id             types.String `tfsdk:"id"`
	LastError      types.String `tfsdk:"last_error"`
	OrganizationId types.String `tfsdk:"organization_id"`
	Status         types.String `tfsdk:"status"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
	ZoneId         types.String `tfsdk:"zone_id"`
}
