// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_user_api_keys

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserApiKeysDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"user_api_keys": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"expires_at": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"last_used_at": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"plain": schema.StringAttribute{
							Computed:            true,
							Description:         "Shown only on create:",
							MarkdownDescription: "Shown only on create:",
						},
						"scope": schema.StringAttribute{
							Computed:            true,
							Description:         "\"user\"",
							MarkdownDescription: "\"user\"",
						},
					},
					CustomType: UserApiKeysType{
						ObjectType: types.ObjectType{
							AttrTypes: UserApiKeysValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type UserApiKeysModel struct {
	UserApiKeys types.Set `tfsdk:"user_api_keys"`
}

var _ basetypes.ObjectTypable = UserApiKeysType{}

type UserApiKeysType struct {
	basetypes.ObjectType
}

func (t UserApiKeysType) Equal(o attr.Type) bool {
	other, ok := o.(UserApiKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserApiKeysType) String() string {
	return "UserApiKeysType"
}

func (t UserApiKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	expiresAtAttribute, ok := attributes["expires_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expires_at is missing from object`)

		return nil, diags
	}

	expiresAtVal, ok := expiresAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expires_at expected to be basetypes.StringValue, was: %T`, expiresAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUsedAtAttribute, ok := attributes["last_used_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_used_at is missing from object`)

		return nil, diags
	}

	lastUsedAtVal, ok := lastUsedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_used_at expected to be basetypes.StringValue, was: %T`, lastUsedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	plainAttribute, ok := attributes["plain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plain is missing from object`)

		return nil, diags
	}

	plainVal, ok := plainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plain expected to be basetypes.StringValue, was: %T`, plainAttribute))
	}

	scopeAttribute, ok := attributes["scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope is missing from object`)

		return nil, diags
	}

	scopeVal, ok := scopeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope expected to be basetypes.StringValue, was: %T`, scopeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserApiKeysValue{
		CreatedAt:  createdAtVal,
		ExpiresAt:  expiresAtVal,
		Id:         idVal,
		LastUsedAt: lastUsedAtVal,
		Name:       nameVal,
		Plain:      plainVal,
		Scope:      scopeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewUserApiKeysValueNull() UserApiKeysValue {
	return UserApiKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewUserApiKeysValueUnknown() UserApiKeysValue {
	return UserApiKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserApiKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserApiKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserApiKeysValue Attribute Value",
				"While creating a UserApiKeysValue value, a missing attribute value was detected. "+
					"A UserApiKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserApiKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserApiKeysValue Attribute Type",
				"While creating a UserApiKeysValue value, an invalid attribute value was detected. "+
					"A UserApiKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserApiKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserApiKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserApiKeysValue Attribute Value",
				"While creating a UserApiKeysValue value, an extra attribute value was detected. "+
					"A UserApiKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserApiKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserApiKeysValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	expiresAtAttribute, ok := attributes["expires_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`expires_at is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	expiresAtVal, ok := expiresAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`expires_at expected to be basetypes.StringValue, was: %T`, expiresAtAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastUsedAtAttribute, ok := attributes["last_used_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_used_at is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	lastUsedAtVal, ok := lastUsedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_used_at expected to be basetypes.StringValue, was: %T`, lastUsedAtAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	plainAttribute, ok := attributes["plain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plain is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	plainVal, ok := plainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plain expected to be basetypes.StringValue, was: %T`, plainAttribute))
	}

	scopeAttribute, ok := attributes["scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope is missing from object`)

		return NewUserApiKeysValueUnknown(), diags
	}

	scopeVal, ok := scopeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope expected to be basetypes.StringValue, was: %T`, scopeAttribute))
	}

	if diags.HasError() {
		return NewUserApiKeysValueUnknown(), diags
	}

	return UserApiKeysValue{
		CreatedAt:  createdAtVal,
		ExpiresAt:  expiresAtVal,
		Id:         idVal,
		LastUsedAt: lastUsedAtVal,
		Name:       nameVal,
		Plain:      plainVal,
		Scope:      scopeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewUserApiKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserApiKeysValue {
	object, diags := NewUserApiKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserApiKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserApiKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserApiKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserApiKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserApiKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserApiKeysValueMust(UserApiKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserApiKeysType) ValueType(ctx context.Context) attr.Value {
	return UserApiKeysValue{}
}

var _ basetypes.ObjectValuable = UserApiKeysValue{}

type UserApiKeysValue struct {
	CreatedAt  basetypes.StringValue `tfsdk:"created_at"`
	ExpiresAt  basetypes.StringValue `tfsdk:"expires_at"`
	Id         basetypes.StringValue `tfsdk:"id"`
	LastUsedAt basetypes.StringValue `tfsdk:"last_used_at"`
	Name       basetypes.StringValue `tfsdk:"name"`
	Plain      basetypes.StringValue `tfsdk:"plain"`
	Scope      basetypes.StringValue `tfsdk:"scope"`
	state      attr.ValueState
}

func (v UserApiKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["expires_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_used_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["plain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["scope"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.ExpiresAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["expires_at"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.LastUsedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_used_at"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Plain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plain"] = val

		val, err = v.Scope.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scope"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserApiKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserApiKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserApiKeysValue) String() string {
	return "UserApiKeysValue"
}

func (v UserApiKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":   basetypes.StringType{},
		"expires_at":   basetypes.StringType{},
		"id":           basetypes.StringType{},
		"last_used_at": basetypes.StringType{},
		"name":         basetypes.StringType{},
		"plain":        basetypes.StringType{},
		"scope":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":   v.CreatedAt,
			"expires_at":   v.ExpiresAt,
			"id":           v.Id,
			"last_used_at": v.LastUsedAt,
			"name":         v.Name,
			"plain":        v.Plain,
			"scope":        v.Scope,
		})

	return objVal, diags
}

func (v UserApiKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(UserApiKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.ExpiresAt.Equal(other.ExpiresAt) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.LastUsedAt.Equal(other.LastUsedAt) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Plain.Equal(other.Plain) {
		return false
	}

	if !v.Scope.Equal(other.Scope) {
		return false
	}

	return true
}

func (v UserApiKeysValue) Type(ctx context.Context) attr.Type {
	return UserApiKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserApiKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":   basetypes.StringType{},
		"expires_at":   basetypes.StringType{},
		"id":           basetypes.StringType{},
		"last_used_at": basetypes.StringType{},
		"name":         basetypes.StringType{},
		"plain":        basetypes.StringType{},
		"scope":        basetypes.StringType{},
	}
}
