// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_user_api_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func UserApiKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"expires_at": schema.StringAttribute{
				Computed: true,
			},
			"expires_in_hours": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "optional TTL",
				MarkdownDescription: "optional TTL",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"last_used_at": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"plain": schema.StringAttribute{
				Computed:            true,
				Description:         "Shown only on create:",
				MarkdownDescription: "Shown only on create:",
			},
			"scope": schema.StringAttribute{
				Computed:            true,
				Description:         "\"user\"",
				MarkdownDescription: "\"user\"",
			},
		},
	}
}

type UserApiKeyModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	ExpiresAt      types.String `tfsdk:"expires_at"`
	ExpiresInHours types.Int64  `tfsdk:"expires_in_hours"`
	Id             types.String `tfsdk:"id"`
	LastUsedAt     types.String `tfsdk:"last_used_at"`
	Name           types.String `tfsdk:"name"`
	Plain          types.String `tfsdk:"plain"`
	Scope          types.String `tfsdk:"scope"`
}
