// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_org_api_key

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OrgApiKeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"expires_at": schema.StringAttribute{
				Computed: true,
			},
			"expires_in_hours": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Org ID (UUID)",
				MarkdownDescription: "Org ID (UUID)",
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"org_key": schema.StringAttribute{
				Computed:            true,
				Description:         "shown once:",
				MarkdownDescription: "shown once:",
			},
			"org_secret": schema.StringAttribute{
				Computed:            true,
				Description:         "shown once:",
				MarkdownDescription: "shown once:",
			},
			"scope": schema.StringAttribute{
				Computed:            true,
				Description:         "\"org\"",
				MarkdownDescription: "\"org\"",
			},
		},
	}
}

type OrgApiKeyModel struct {
	CreatedAt      types.String `tfsdk:"created_at"`
	ExpiresAt      types.String `tfsdk:"expires_at"`
	ExpiresInHours types.Int64  `tfsdk:"expires_in_hours"`
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	OrgKey         types.String `tfsdk:"org_key"`
	OrgSecret      types.String `tfsdk:"org_secret"`
	Scope          types.String `tfsdk:"scope"`
}
