package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	resourceschema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

var (
	_ resource.Resource                = &clusterResource{}
	_ resource.ResourceWithConfigure   = &clusterResource{}
	_ resource.ResourceWithImportState = &clusterResource{}
)

type clusterResource struct {
	client *autoglueClient
}

type clusterResourceModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`

	ClusterProvider types.String `tfsdk:"cluster_provider"`
	Region          types.String `tfsdk:"region"`

	Status         types.String `tfsdk:"status"`
	LastError      types.String `tfsdk:"last_error"`
	RandomToken    types.String `tfsdk:"random_token"`
	CertificateKey types.String `tfsdk:"certificate_key"`

	CaptainDomainID         types.String `tfsdk:"captain_domain_id"`
	ControlPlaneRecordSetID types.String `tfsdk:"control_plane_record_set_id"`
	ControlPlaneFQDN        types.String `tfsdk:"control_plane_fqdn"`
	AppsLoadBalancerID      types.String `tfsdk:"apps_load_balancer_id"`
	GlueOpsLoadBalancerID   types.String `tfsdk:"glueops_load_balancer_id"`
	BastionServerID         types.String `tfsdk:"bastion_server_id"`

	CreatedAt types.String `tfsdk:"created_at"`
	UpdatedAt types.String `tfsdk:"updated_at"`
}

func NewClusterResource() resource.Resource {
	return &clusterResource{}
}

func (r *clusterResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cluster"
}

func (r *clusterResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resourceschema.Schema{
		Description: "Manages an Autoglue cluster (name, provider, region). " +
			"Attachments such as domains, record sets, load balancers, bastion and node pools are managed via separate resources.",
		Attributes: map[string]resourceschema.Attribute{
			"id": resourceschema.StringAttribute{
				Computed:    true,
				Description: "Cluster ID.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},

			"name": resourceschema.StringAttribute{
				Required:    true,
				Description: "Cluster name.",
			},

			"cluster_provider": resourceschema.StringAttribute{
				Required:    true,
				Description: "Cluster provider identifier (e.g. aws, azure, gcp).",
			},

			"region": resourceschema.StringAttribute{
				Required:    true,
				Description: "Cluster region identifier.",
			},

			"status": resourceschema.StringAttribute{
				Computed:    true,
				Description: "Cluster status (e.g. pre_pending, ready, failed).",
			},

			"last_error": resourceschema.StringAttribute{
				Computed:    true,
				Description: "Last validation/provisioning error, if any.",
			},

			"random_token": resourceschema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "Random token generated by the control plane for this cluster.",
			},

			"certificate_key": resourceschema.StringAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "Cluster certificate key generated by the control plane.",
			},

			"captain_domain_id": resourceschema.StringAttribute{
				Computed:    true,
				Description: "ID of the captain domain attached to this cluster, if any.",
			},

			"control_plane_record_set_id": resourceschema.StringAttribute{
				Computed:    true,
				Description: "ID of the control plane record set attached to this cluster, if any.",
			},

			"control_plane_fqdn": resourceschema.StringAttribute{
				Computed:    true,
				Description: "Effective control-plane FQDN if both domain and record set are attached.",
			},

			"apps_load_balancer_id": resourceschema.StringAttribute{
				Computed:    true,
				Description: "ID of the apps load balancer attached to this cluster, if any.",
			},

			"glueops_load_balancer_id": resourceschema.StringAttribute{
				Computed:    true,
				Description: "ID of the GlueOps/control-plane load balancer attached to this cluster, if any.",
			},

			"bastion_server_id": resourceschema.StringAttribute{
				Computed:    true,
				Description: "ID of the bastion server attached to this cluster, if any.",
			},

			"created_at": resourceschema.StringAttribute{
				Computed:    true,
				Description: "Creation timestamp (RFC3339).",
			},

			"updated_at": resourceschema.StringAttribute{
				Computed:    true,
				Description: "Last update timestamp (RFC3339).",
			},
		},
	}
}

func (r *clusterResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*autoglueClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data type",
			fmt.Sprintf("Expected *autoglueClient, got %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *clusterResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client not configured", "The provider client was not configured.")
		return
	}

	var plan clusterResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	payload := createClusterPayload{
		Name:            plan.Name.ValueString(),
		ClusterProvider: plan.ClusterProvider.ValueString(),
		Region:          plan.Region.ValueString(),
	}

	tflog.Info(ctx, "Creating Autoglue cluster", map[string]any{
		"name":             payload.Name,
		"cluster_provider": payload.ClusterProvider,
		"region":           payload.Region,
	})

	var apiResp cluster
	if err := r.client.doJSON(ctx, http.MethodPost, "/clusters", "", payload, &apiResp); err != nil {
		resp.Diagnostics.AddError("Error creating cluster", err.Error())
		return
	}

	syncClusterFromAPI(&plan, &apiResp)

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *clusterResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client not configured", "The provider client was not configured.")
		return
	}

	var state clusterResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := state.ID.ValueString()
	if id == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	path := fmt.Sprintf("/clusters/%s", id)
	tflog.Info(ctx, "Reading Autoglue cluster", map[string]any{"id": id})

	var apiResp cluster
	if err := r.client.doJSON(ctx, http.MethodGet, path, "", nil, &apiResp); err != nil {
		// If not found, drop from state
		resp.State.RemoveResource(ctx)
		return
	}

	syncClusterFromAPI(&state, &apiResp)

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *clusterResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client not configured", "The provider client was not configured.")
		return
	}

	var plan clusterResourceModel
	var state clusterResourceModel

	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := state.ID.ValueString()
	if id == "" {
		resp.Diagnostics.AddError("Missing ID", "Cluster ID is required in state to update cluster.")
		return
	}

	var payload updateClusterPayload
	if !plan.Name.Equal(state.Name) {
		v := plan.Name.ValueString()
		payload.Name = &v
	}
	if !plan.ClusterProvider.Equal(state.ClusterProvider) {
		v := plan.ClusterProvider.ValueString()
		payload.ClusterProvider = &v
	}
	if !plan.Region.Equal(state.Region) {
		v := plan.Region.ValueString()
		payload.Region = &v
	}

	if payload.Name == nil && payload.ClusterProvider == nil && payload.Region == nil {
		// Nothing to update
		return
	}

	path := fmt.Sprintf("/clusters/%s", id)

	tflog.Info(ctx, "Updating Autoglue cluster", map[string]any{
		"id":               id,
		"name":             plan.Name.ValueString(),
		"cluster_provider": plan.ClusterProvider.ValueString(),
		"region":           plan.Region.ValueString(),
	})

	var apiResp cluster
	if err := r.client.doJSON(ctx, http.MethodPatch, path, "", payload, &apiResp); err != nil {
		resp.Diagnostics.AddError("Error updating cluster", err.Error())
		return
	}

	syncClusterFromAPI(&plan, &apiResp)

	diags = resp.State.Set(ctx, &plan)
	resp.Diagnostics.Append(diags...)
}

func (r *clusterResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	if r.client == nil {
		resp.Diagnostics.AddError("Client not configured", "The provider client was not configured.")
		return
	}

	var state clusterResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	id := state.ID.ValueString()
	if id == "" {
		return
	}

	path := fmt.Sprintf("/clusters/%s", id)
	tflog.Info(ctx, "Deleting Autoglue cluster", map[string]any{"id": id})

	if err := r.client.doJSON(ctx, http.MethodDelete, path, "", nil, nil); err != nil {
		resp.Diagnostics.AddError("Error deleting cluster", err.Error())
		return
	}

	resp.State.RemoveResource(ctx)
}

func (r *clusterResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// terraform import autoglue_cluster.example <cluster_id>
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func syncClusterFromAPI(state *clusterResourceModel, api *cluster) {
	state.ID = types.StringValue(api.ID)
	state.Name = types.StringValue(api.Name)
	state.ClusterProvider = types.StringValue(api.ClusterProvider)
	state.Region = types.StringValue(api.Region)
	state.Status = types.StringValue(api.Status)
	state.LastError = types.StringValue(api.LastError)
	state.RandomToken = types.StringValue(api.RandomToken)
	state.CertificateKey = types.StringValue(api.CertificateKey)
	state.CreatedAt = types.StringValue(api.CreatedAt)
	state.UpdatedAt = types.StringValue(api.UpdatedAt)

	if api.CaptainDomain != nil {
		state.CaptainDomainID = types.StringValue(api.CaptainDomain.ID)
	} else {
		state.CaptainDomainID = types.StringNull()
	}
	if api.ControlPlaneRecordSet != nil {
		state.ControlPlaneRecordSetID = types.StringValue(api.ControlPlaneRecordSet.ID)
	} else {
		state.ControlPlaneRecordSetID = types.StringNull()
	}
	if api.ControlPlaneFQDN != nil {
		state.ControlPlaneFQDN = types.StringValue(*api.ControlPlaneFQDN)
	} else {
		state.ControlPlaneFQDN = types.StringNull()
	}
	if api.AppsLoadBalancer != nil {
		state.AppsLoadBalancerID = types.StringValue(api.AppsLoadBalancer.ID)
	} else {
		state.AppsLoadBalancerID = types.StringNull()
	}
	if api.GlueOpsLoadBalancer != nil {
		state.GlueOpsLoadBalancerID = types.StringValue(api.GlueOpsLoadBalancer.ID)
	} else {
		state.GlueOpsLoadBalancerID = types.StringNull()
	}
	if api.BastionServer != nil {
		state.BastionServerID = types.StringValue(api.BastionServer.ID)
	} else {
		state.BastionServerID = types.StringNull()
	}
}
