// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_record_set

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RecordSetResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"domain_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Domain ID (UUID)",
				MarkdownDescription: "Domain ID (UUID)",
			},
			"fingerprint": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"last_error": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name relative to domain (\"endpoint\") OR FQDN (\"endpoint.example.com\").\nServer normalizes to relative.",
				MarkdownDescription: "Name relative to domain (\"endpoint\") OR FQDN (\"endpoint.example.com\").\nServer normalizes to relative.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(253),
				},
			},
			"owner": schema.StringAttribute{
				Computed: true,
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "pending|provisioning|ready|failed",
				MarkdownDescription: "pending|provisioning|ready|failed",
			},
			"ttl": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(1, 86400),
				},
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "RR type (A, AAAA, CNAME, TXT, MX, NS, SRV, CAA)",
				MarkdownDescription: "RR type (A, AAAA, CNAME, TXT, MX, NS, SRV, CAA)",
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"values": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

type RecordSetModel struct {
	CreatedAt   types.String `tfsdk:"created_at"`
	DomainId    types.String `tfsdk:"domain_id"`
	Fingerprint types.String `tfsdk:"fingerprint"`
	Id          types.String `tfsdk:"id"`
	LastError   types.String `tfsdk:"last_error"`
	Name        types.String `tfsdk:"name"`
	Owner       types.String `tfsdk:"owner"`
	Status      types.String `tfsdk:"status"`
	Ttl         types.Int64  `tfsdk:"ttl"`
	Type        types.String `tfsdk:"type"`
	UpdatedAt   types.String `tfsdk:"updated_at"`
	Values      types.List   `tfsdk:"values"`
}
