// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_server_reset_hostkey

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServerResetHostkeyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"hostname": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Server ID (UUID)",
				MarkdownDescription: "Server ID (UUID)",
			},
			"organization_id": schema.StringAttribute{
				Computed: true,
			},
			"private_ip_address": schema.StringAttribute{
				Computed: true,
			},
			"public_ip_address": schema.StringAttribute{
				Computed: true,
			},
			"role": schema.StringAttribute{
				Computed: true,
			},
			"ssh_key_id": schema.StringAttribute{
				Computed: true,
			},
			"ssh_user": schema.StringAttribute{
				Computed: true,
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type ServerResetHostkeyModel struct {
	CreatedAt        types.String `tfsdk:"created_at"`
	Hostname         types.String `tfsdk:"hostname"`
	Id               types.String `tfsdk:"id"`
	OrganizationId   types.String `tfsdk:"organization_id"`
	PrivateIpAddress types.String `tfsdk:"private_ip_address"`
	PublicIpAddress  types.String `tfsdk:"public_ip_address"`
	Role             types.String `tfsdk:"role"`
	SshKeyId         types.String `tfsdk:"ssh_key_id"`
	SshUser          types.String `tfsdk:"ssh_user"`
	Status           types.String `tfsdk:"status"`
	UpdatedAt        types.String `tfsdk:"updated_at"`
}
