// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_domains

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DomainsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"domain_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Exact domain name (lowercase, no trailing dot)",
				MarkdownDescription: "Exact domain name (lowercase, no trailing dot)",
			},
			"domains": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed: true,
						},
						"credential_id": schema.StringAttribute{
							Computed: true,
						},
						"domain_name": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"last_error": schema.StringAttribute{
							Computed: true,
						},
						"organization_id": schema.StringAttribute{
							Computed: true,
						},
						"status": schema.StringAttribute{
							Computed: true,
						},
						"updated_at": schema.StringAttribute{
							Computed: true,
						},
						"zone_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DomainsType{
						ObjectType: types.ObjectType{
							AttrTypes: DomainsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"q": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Domain contains (case-insensitive)",
				MarkdownDescription: "Domain contains (case-insensitive)",
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "pending|provisioning|ready|failed",
				MarkdownDescription: "pending|provisioning|ready|failed",
			},
		},
	}
}

type DomainsModel struct {
	DomainName types.String `tfsdk:"domain_name"`
	Domains    types.Set    `tfsdk:"domains"`
	Q          types.String `tfsdk:"q"`
	Status     types.String `tfsdk:"status"`
}

var _ basetypes.ObjectTypable = DomainsType{}

type DomainsType struct {
	basetypes.ObjectType
}

func (t DomainsType) Equal(o attr.Type) bool {
	other, ok := o.(DomainsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DomainsType) String() string {
	return "DomainsType"
}

func (t DomainsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	credentialIdAttribute, ok := attributes["credential_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credential_id is missing from object`)

		return nil, diags
	}

	credentialIdVal, ok := credentialIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credential_id expected to be basetypes.StringValue, was: %T`, credentialIdAttribute))
	}

	domainNameAttribute, ok := attributes["domain_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`domain_name is missing from object`)

		return nil, diags
	}

	domainNameVal, ok := domainNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`domain_name expected to be basetypes.StringValue, was: %T`, domainNameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastErrorAttribute, ok := attributes["last_error"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_error is missing from object`)

		return nil, diags
	}

	lastErrorVal, ok := lastErrorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_error expected to be basetypes.StringValue, was: %T`, lastErrorAttribute))
	}

	organizationIdAttribute, ok := attributes["organization_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization_id is missing from object`)

		return nil, diags
	}

	organizationIdVal, ok := organizationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization_id expected to be basetypes.StringValue, was: %T`, organizationIdAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return nil, diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DomainsValue{
		CreatedAt:      createdAtVal,
		CredentialId:   credentialIdVal,
		DomainName:     domainNameVal,
		Id:             idVal,
		LastError:      lastErrorVal,
		OrganizationId: organizationIdVal,
		Status:         statusVal,
		UpdatedAt:      updatedAtVal,
		ZoneId:         zoneIdVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewDomainsValueNull() DomainsValue {
	return DomainsValue{
		state: attr.ValueStateNull,
	}
}

func NewDomainsValueUnknown() DomainsValue {
	return DomainsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDomainsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DomainsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DomainsValue Attribute Value",
				"While creating a DomainsValue value, a missing attribute value was detected. "+
					"A DomainsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DomainsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DomainsValue Attribute Type",
				"While creating a DomainsValue value, an invalid attribute value was detected. "+
					"A DomainsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DomainsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DomainsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DomainsValue Attribute Value",
				"While creating a DomainsValue value, an extra attribute value was detected. "+
					"A DomainsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DomainsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDomainsValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	credentialIdAttribute, ok := attributes["credential_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`credential_id is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	credentialIdVal, ok := credentialIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`credential_id expected to be basetypes.StringValue, was: %T`, credentialIdAttribute))
	}

	domainNameAttribute, ok := attributes["domain_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`domain_name is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	domainNameVal, ok := domainNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`domain_name expected to be basetypes.StringValue, was: %T`, domainNameAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	lastErrorAttribute, ok := attributes["last_error"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_error is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	lastErrorVal, ok := lastErrorAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_error expected to be basetypes.StringValue, was: %T`, lastErrorAttribute))
	}

	organizationIdAttribute, ok := attributes["organization_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization_id is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	organizationIdVal, ok := organizationIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization_id expected to be basetypes.StringValue, was: %T`, organizationIdAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	zoneIdAttribute, ok := attributes["zone_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`zone_id is missing from object`)

		return NewDomainsValueUnknown(), diags
	}

	zoneIdVal, ok := zoneIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`zone_id expected to be basetypes.StringValue, was: %T`, zoneIdAttribute))
	}

	if diags.HasError() {
		return NewDomainsValueUnknown(), diags
	}

	return DomainsValue{
		CreatedAt:      createdAtVal,
		CredentialId:   credentialIdVal,
		DomainName:     domainNameVal,
		Id:             idVal,
		LastError:      lastErrorVal,
		OrganizationId: organizationIdVal,
		Status:         statusVal,
		UpdatedAt:      updatedAtVal,
		ZoneId:         zoneIdVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewDomainsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DomainsValue {
	object, diags := NewDomainsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDomainsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DomainsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDomainsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDomainsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDomainsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDomainsValueMust(DomainsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DomainsType) ValueType(ctx context.Context) attr.Value {
	return DomainsValue{}
}

var _ basetypes.ObjectValuable = DomainsValue{}

type DomainsValue struct {
	CreatedAt      basetypes.StringValue `tfsdk:"created_at"`
	CredentialId   basetypes.StringValue `tfsdk:"credential_id"`
	DomainName     basetypes.StringValue `tfsdk:"domain_name"`
	Id             basetypes.StringValue `tfsdk:"id"`
	LastError      basetypes.StringValue `tfsdk:"last_error"`
	OrganizationId basetypes.StringValue `tfsdk:"organization_id"`
	Status         basetypes.StringValue `tfsdk:"status"`
	UpdatedAt      basetypes.StringValue `tfsdk:"updated_at"`
	ZoneId         basetypes.StringValue `tfsdk:"zone_id"`
	state          attr.ValueState
}

func (v DomainsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["credential_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["domain_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_error"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["organization_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["zone_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CredentialId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["credential_id"] = val

		val, err = v.DomainName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["domain_name"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.LastError.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_error"] = val

		val, err = v.OrganizationId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["organization_id"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		val, err = v.ZoneId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["zone_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DomainsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DomainsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DomainsValue) String() string {
	return "DomainsValue"
}

func (v DomainsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":      basetypes.StringType{},
		"credential_id":   basetypes.StringType{},
		"domain_name":     basetypes.StringType{},
		"id":              basetypes.StringType{},
		"last_error":      basetypes.StringType{},
		"organization_id": basetypes.StringType{},
		"status":          basetypes.StringType{},
		"updated_at":      basetypes.StringType{},
		"zone_id":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":      v.CreatedAt,
			"credential_id":   v.CredentialId,
			"domain_name":     v.DomainName,
			"id":              v.Id,
			"last_error":      v.LastError,
			"organization_id": v.OrganizationId,
			"status":          v.Status,
			"updated_at":      v.UpdatedAt,
			"zone_id":         v.ZoneId,
		})

	return objVal, diags
}

func (v DomainsValue) Equal(o attr.Value) bool {
	other, ok := o.(DomainsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CredentialId.Equal(other.CredentialId) {
		return false
	}

	if !v.DomainName.Equal(other.DomainName) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.LastError.Equal(other.LastError) {
		return false
	}

	if !v.OrganizationId.Equal(other.OrganizationId) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	if !v.ZoneId.Equal(other.ZoneId) {
		return false
	}

	return true
}

func (v DomainsValue) Type(ctx context.Context) attr.Type {
	return DomainsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DomainsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":      basetypes.StringType{},
		"credential_id":   basetypes.StringType{},
		"domain_name":     basetypes.StringType{},
		"id":              basetypes.StringType{},
		"last_error":      basetypes.StringType{},
		"organization_id": basetypes.StringType{},
		"status":          basetypes.StringType{},
		"updated_at":      basetypes.StringType{},
		"zone_id":         basetypes.StringType{},
	}
}
